version: '3.1'
services: 
    db:
        container_name: buybox-db
        image: mariadb:10.3
        volumes: 
            - ./BuyBox.SQL/:/sql/
        ports: 
            - "3306:3306"
        environment: 
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_DATABASE=buybox
            - MYSQL_USER=buybox
            - MYSQL_PASSWORD=password