version: '3.1'
networks: 
    net:
services: 
    # Maria DB Database for the application
    buybox-db:
        image: mariadb:10.3
        container_name: buybox-db
        volumes: 
            - ./BuyBox.SQL/:/sql/
        ports: 
            - "3306:3306"
        environment: 
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_DATABASE=buybox
            - MYSQL_USER=buybox
            - MYSQL_PASSWORD=password
    
    # C# .Net Core Api for the Application Services
    buybox-api:
        image: mcr.microsoft.com/dotnet/core/sdk:3.1
        container_name: buybox-api
        hostname: buybox.local
        working_dir: /api/
        command: dotnet ./BuyBox.Api.dll
        restart: always
        environment: 
            ASPNETCORE_URLS: http://*:8000
        ports: 
            - "8000:8000"
        volumes: 
            - ./BuyBox.Api/dist/BuyBox.Api/:/api/
        links: 
            - buybox-db

    # Angular-CLI Application
    buybox-web:
        image: nginx:alpine
        container_name: buybox-web
        hostname: buybox.local
        networks: 
            net: 
                aliases: 
                    - buybox.local
        ports: 
            - "80:80"
        volumes: 
            - ./BuyBox/dist/BuyBox/:/usr/share/nginx/html