version: '3.1'
services: 
    #
    db:
        container_name: buybox-db
        image: mariadb:10.3
        volumes: 
            - ./BuyBox.SQL/:/sql/
        ports: 
            - "3306:3306"
        environment: 
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_DATABASE=buybox
            - MYSQL_USER=buybox
            - MYSQL_PASSWORD=password
    
    #C# .Net Core Api for the Application Services
    api:
        container_name: lifehack-api
        working_dir: /api/
        image: mcr.microsoft.com/dotnet/core/sdk:3.1
        command: dotnet ./BuyBox.Api.dll
        restart: always
        environment: 
            ASPNETCORE_ENVIRONMENT: Development
            ASPNETCORE_URLS: http://*:8000
        ports:
            - "8000:8000"
        volumes: 
            - ./wwwroot/api/:/api/